import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import getDate from "@matthew-vance/get-date"
import sayHi from "@matthew-vance/say-hi"

const Home: NextPage = () => {
  const date = getDate();
  const hiMessage = sayHi("Matt");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          {`${hiMessage} Today is ${date}.`}
        </p>
      </main>
    </div>
  )
}

export default Home
